### ISSUE TITLE
Why SVN?

### ISSUE THREAD

**Issue by nwinkler** [caskroom/homebrew-fonts#309]
A general question: Why are the font downloads (at least for the ones that I've checked) default to using `svn` for the checkout? Why aren't they using `git`?

I'm asking since I'm working behind a corporate proxy, and my Git configuration is set up to work through the proxy, but my SVN configuration isn't. Using the regular `brew` and `brew-cask` commands works fine for everything else, since all of the other projects are using Git, except this one.

Is there any specific reason for using SVN instead of Git for the downloads?

**Comment by ndr-qef** [comment]
We use SVN for fonts distributed by the Google Fonts project.

Most OTF/TTF files from Google Fonts can only be retrieved from a public [Git repository](https://github.com/google/fonts), where each font family lives in a subfolder. Because Git works on a “whole repository” basis, the only way to fetch one such subfolder as a single downloadable resource (which is currently a requirement for Homebrew-cask) is to use SVN.

**Comment by nwinkler** [comment]
Thanks for the explanation - that makes sense. I have added a local proxy configuration for SVN, and now the checkout works for me as well when at work.
