### ISSUE TITLE
Issue reported from `brew doctor`

### ISSUE THREAD

**Issue by beardedprojamz** [caskroom/homebrew-fonts#329]
After a `brew update`, `brew doctor` is now complaining about `font-fira-code`:

```
Error: Failed to import: font-fira-code
undefined method `cask' for Formulary::Formulae:Module
```

Any ideas how to fix that?

**Comment by mskblackbelt** [comment]
Seconded, and I can't seem to find reference to `font-fira-code` in the homebrew-fonts listing… 
Running `brew cask doctor` results in a clean report; this problem only occurs when running `brew doctor`. 

The formula is located out of place, in the root `homebrew-fonts` folder, rather than the `homebrew-fonts/Casks` sub-folder. Moving the file into the `Casks` sub-folder changes the resultant `brew doctor` error to: 
```
Error: Failed to import: font-fira-code
No available formula for font-fira-code
```
However, `brew cask install font-fira-code` is successful after the move is performed. 

Any other ideas for repair? Is this a problem with how `brew` registers/searches for Casks?

**Comment by cwonrails** [comment]
+1

**Comment by ndr-qef** [comment]
Thanks, fixed in 2f0453.

After running `brew update`, the output of `brew doctor` should now be clean.
