### ISSUE TITLE
Cannot install font-open-sans

### ISSUE THREAD

**Issue by niggusch** [caskroom/homebrew-fonts#443]
It seams that the git repository does not exist (anymore)?

```
$ brew cask install font-open-sans
==> Checking out https://github.com/google/fonts/trunk/apache/opensans
Error: Download failed on Cask 'font-open-sans' with message: Command failed to execute!

==> Failed command:
["/usr/bin/svn", "checkout", "--force", "--config-option", "config:miscellany:use-commit-times=yes", "--trust-server-cert", "--non-interactive", "https://github.com/google/fonts/trunk/apache/opensans", "#<Pathname:/Library/Caches/Homebrew/font-open-sans--svn>", "-r", "48"]

==> Output of failed command:


==> Exit status of failed command:
#<Process::Status: pid 1833 exit 1>
```

**Comment by vitorgalvao** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.
