### ISSUE TITLE
font-iosevka: "Error: It seems the hardlink source is not there"

### ISSUE THREAD

**Issue by pvinis** [caskroom/homebrew-fonts#576]
im trying to update iosevka from 1.8.0 to 1.8.4. i updated the formula here https://github.com/caskroom/homebrew-fonts/pull/572/files and again here https://github.com/caskroom/homebrew-fonts/pull/575.

after both updates, im getting this 
```
==> Verifying checksum for Cask font-iosevka
Error: It seems the hardlink source is not there: '/opt/homebrew-cask/Caskroom/font-iosevka/1.8.4/font-iosevka-1.8.4/iosevka-bold.ttf'
Error: Kernel.exit
```
i did the second update because i thought that was the problem, but apparently not.
what is the problem? or how can i test the cask locally (and maybe more verbosely) so maybe i can figure it out by myself?

**Comment by vitorgalvao** [comment]
The problem is it’s trying to access something that isn’t there. From your fixes, I’d say you are on the right track and understand what needs to be done, just aren’t there, yet.

To test it locally, simply give the local file as the argument. So assuming you’re at `<whatever_path>/homebrew-fonts/Casks`, you’d to `brew cask install ./<cask-name>.rb`.

**Comment by chuchana** [comment]
Could you roll back to version 1.8.0 until this is fixed?

**Comment by adidalal** [comment]
Fixed. https://github.com/caskroom/homebrew-fonts/pull/583

**Comment by chuchana** [comment]
@adidalal Thank you!

**Comment by pvinis** [comment]
@adidalal thanks. i was off the grid for a week.. sorry.
